<OPTION VALUE=""> 
<OPTION VALUE="STF001">Attending a conference/workshop/seminar as a participant
<OPTION VALUE="STF002">Presenting a research paper at a conference/workshop/seminar
<OPTION VALUE="STF003">Speaking at a conference/workshop/seminar
<OPTION VALUE="STF004">Fieldwork for research project
<OPTION VALUE="STF005">Visiting a university/collaborator for discussion on research project
<OPTION VALUE="STF999">Others